apiVersion: v1
kind: ServiceAccount
metadata:
  name: ganglia
  namespace: ganglia
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ganglia
  namespace: ganglia
rules:
- apiGroups: ["*"]
  verbs: ["get","list","watch","patch"]
  resources: ["pods","services"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  ganglia
  namespace: ganglia
subjects:
  - kind: ServiceAccount
    name: ganglia
    namespace: ganglia
roleRef:
  kind: Role
  name: ganglia
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ganglia
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ganglia
subjects:
- kind: ServiceAccount
  name: ganglia
  namespace: ganglia
roleRef:
  kind: ClusterRole
  name: ganglia
  apiGroup: rbac.authorization.k8s.io
